---
- name: Setting up LAMP Website
  hosts: localhost
  become: yes
  tasks:
    - name:  install all services
      yum:
         name:
           - firewalld
           - httpd
           - mariadb-server
           - php
           - php-mysql
         state: latest

    - name: firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started

    - name: mariadb enabled and running
      service:
        name: mariadb
        enabled: true
        state: started

    
